Generated from base-vm

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -52,7 +52,6 @@ jobs:
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
-      SEC_VBOX : ${{ vars.SEC_VBOX }}
       DEBUG: 1
       GH_TOKEN: ${{ secrets.GH_TOKEN }}
     steps:
@@ -195,7 +194,6 @@ jobs:
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
-      SEC_VBOX : ${{ vars.SEC_VBOX }}
       DEBUG: 1
       GH_TOKEN: ${{ secrets.GH_TOKEN }}
     steps:
@@ -338,7 +336,6 @@ jobs:
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
-      SEC_VBOX : ${{ vars.SEC_VBOX }}
       DEBUG: 1
       GH_TOKEN: ${{ secrets.GH_TOKEN }}
     steps:
@@ -467,7 +464,6 @@ jobs:
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
-      SEC_VBOX : ${{ vars.SEC_VBOX }}
       GH_TOKEN: ${{ secrets.GH_TOKEN }}
     steps:
     - uses: actions/checkout@v6
@@ -561,6 +557,67 @@ jobs:
           whoami
           env
           echo "OK"
+
+
+
+
+
+  testerr:
+    strategy:
+      fail-fast: false
+    runs-on: ubuntu-24.04
+    name: test default error Haiku
+    steps:
+    - uses: actions/checkout@v6
+    - name: Test in Haiku
+      id: testerr
+      continue-on-error: true 
+      uses: vmactions/haiku-vm@dc863fe44a648dcce6c21930389b1d30262749a8
+      with:
+        usesh: true
+        debug: true
+        run: |
+          echo "this is an error"
+          exit 1
+    - name: Verify that the previous step failed
+      if: steps.testerr.outcome != 'failure'
+      run: |
+        echo "The step was expected to fail, but it succeeded!"
+        exit 1
+    - name: Verify that the previous step succeeded
+      if: steps.testerr.outcome == 'failure'
+      run: |
+        echo "The step was expected to fail, and it failed!"
+        exit 0
+
+  testpass:
+    strategy:
+      fail-fast: false
+    runs-on: ubuntu-24.04
+    name: test default success Haiku
+    steps:
+    - uses: actions/checkout@v6
+    - name: Test in Haiku
+      id: testpass
+      continue-on-error: true 
+      uses: vmactions/haiku-vm@dc863fe44a648dcce6c21930389b1d30262749a8
+      with:
+        usesh: true
+        debug: true
+        run: |
+          echo "this is a normal command"
+          exit 0
+    - name: Verify that the previous step succeeded
+      if: steps.testpass.outcome != 'success'
+      run: |
+        echo "The step was expected to succeed, but it failed!"
+        exit 1
+    - name: Verify that the previous step failed
+      if: steps.testpass.outcome == 'success'
+      run: |
+        echo "The step was expected to succeed, and it succeeded!"
+        exit 0
+
 
 
 
